package be.virtualsushi.jfx.dorse.navigation;

public enum AppActivitiesNames {

	HOME, TEST, EDIT_INVOICE, EDIT_CUSTOMER, EDIT_ARTICLE, LIST_INVOICES, LIST_CUSTOMERS, LIST_ARTICLES, VIEW_ARTICLE, VIEW_CUSTOMER, VIEW_INVOICE;

}
