package be.virtualsushi.jfx.dorse.navigation;

public enum AppActivitiesNames {

	HOME, TEST, LOGOUT, EDIT_INVOICE, EDIT_CUSTOMER, EDIT_ARTICLE, EDIT_POST, LIST_INVOICES, LIST_CUSTOMERS, LIST_ARTICLES, LIST_POST, VIEW_ARTICLE, VIEW_CUSTOMER, VIEW_INVOICE, VIEW_POST;

}
